### ISSUE TITLE
german translation

### ISSUE THREAD

**Issue by ManfredWisniewski** [wearerequired/user-feedback#41]
Hello
I created a german translation for your plugin. However I don't really know how GitHub works yet and I cant figure out where or how to add it. (like the norwegian translation) If you let me know how to get it to you I would like to offer it for the project. (Can only add pictures here) :(

**Comment by swissspidy** [comment]
Hey Manfred

Thanks for translating all those strings!

You can submit a pull request here on the `develop` branch. I recommend you to check out [this guide](https://help.github.com/articles/using-pull-requests/) in order to see how pull requests work. Alternatively you can also send us the files [via email](https://github.com/wearerequired/user-feedback/blob/develop/user-feedback.php#L17) if you want.

**Comment by swissspidy** [comment]
Closing for now. There might be lots of string changes in the future anyway, so let's wait for this.
